import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en');

    const translations = {
        en: {
            title: 'Nexus English',
            chat: 'Chat',
            myAgents: 'My Agents',
            marketplace: 'Marketplace',
            settings: 'Settings',
            adminDashboard: 'Admin Dashboard',
            notifications: 'Notifications',
            personalProfile: 'Personal Profile',
            helpFaq: 'Help & FAQ',
            signOut: 'Sign Out',
            language: 'Language',
            mode: 'Mode',
            light: 'LIGHT',
            dark: 'DARK',
            activeConnection: 'Active Connection',
            typeMessage: 'Type your secure message...',
            privateSupport: 'Private Support',
            secureProtocol: 'SECURE PROTOCOL ACTIVE',
            history: 'History',
            newInstance: 'New Instance',
            memoryEmpty: 'Memory Empty',
            initializeLogic: 'INITIALIZE LOGIC',
            chatGreeting: 'Your advanced AI agent is calibrated and ready for interaction. How can we optimize your workflow today?',
            askPlaceholder: 'Ask Aisa...',
            my: 'My',
            agentsHeading: 'Agents.',
            manageAgentsDesc: 'Manage your collection of AI agents.',
            docs: 'Docs',
            use: 'USE',
            info: 'Info',
            marketplaceHeading: 'AI MALL MARKETPLACE',
            marketplaceSubheading: 'DISCOVER INTELLIGENT AGENTS',
            aiAgents: 'AI AGENTS',
            searchPlaceholder: 'SEARCH AGENTS...',
            viewInfo: 'VIEW INFO',
            notificationsHeading: 'Notifications',
            notificationsDesc: 'Stay updated with your latest alerts.',
            markAsRead: 'MARK AS READ',
            delete: 'DELETE',
            noNotificationsTitle: 'Null Void Sequence',
            noNotificationsDesc: 'No neural transmissions detected. Your ecosystem is currently reaching peak stability.',
            onlineReady: 'Online & Ready',
            processingReality: 'Processing Reality',
            synced: 'SYNCED',
            untitledSession: 'Untitled Session',
            cancel: 'CANCEL',
            subscribeNow: 'SUBSCRIBE NOW'
        },
        ar: {
            title: 'العربية (Arabic)',
            chat: 'محادثة',
            myAgents: 'وكلائي',
            marketplace: 'المتجر',
            settings: 'الإعدادات',
            adminDashboard: 'لوحة التحكم',
            notifications: 'الإشعارات',
            personalProfile: 'الملف الشخصي',
            helpFaq: 'المساعدة والأسئلة الشائعة',
            signOut: 'تسجيل الخروج',
            language: 'اللغة',
            mode: 'الوضع',
            light: 'فاتح',
            dark: 'داكن',
            activeConnection: 'اتصال نشط',
            typeMessage: 'اكتب رسالتك الآمنة...',
            privateSupport: 'دعم خاص',
            secureProtocol: 'بروتوكول آمن نشط',
            history: 'السجل',
            newInstance: 'مثيل جديد',
            memoryEmpty: 'الذاكرة فارغة',
            initializeLogic: 'تهيئة المنطق',
            chatGreeting: 'وكيل الذكاء الاصطناعي المتقدم الخاص بك جاهز للتفاعل. كيف يمكننا تحسين سير عملك اليوم؟',
            askPlaceholder: 'اسأل عيسى...',
            my: 'وكلائي',
            agentsHeading: 'وكلاء',
            manageAgentsDesc: 'إدارة مجموعة وكلاء الذكاء الاصطناعي الخاصة بك.',
            docs: 'الوثائق',
            use: 'استخدام',
            info: 'معلومات',
            marketplaceHeading: 'متجر آي مول',
            marketplaceSubheading: 'اكتشف الوكلاء الأذكياء',
            aiAgents: 'وكلاء الذكاء الاصطناعي',
            searchPlaceholder: 'البحث عن وكلاء...',
            viewInfo: 'عرض المعلومات',
            notificationsHeading: 'الإشعارات',
            notificationsDesc: 'ابق على اطلاع بآخر التنبيهات.',
            markAsRead: 'تحديد كقروء',
            delete: 'حذف',
            noNotificationsTitle: 'تسلسل فارغ',
            noNotificationsDesc: 'لم يتم اكتشاف أي إرسالات عصبية. نظامك البيئي يصل حاليًا إلى ذروة الاستقرار.',
            onlineReady: 'متصل وجاهز',
            processingReality: 'معالجة الواقع',
            synced: 'متزامن',
            untitledSession: 'جلسة بدون عنوان',
            cancel: 'إلغاء',
            subscribeNow: 'اشترك الآن'
        },
        hi: {
            title: 'हिन्दी (Hindi)',
            chat: 'चैट',
            myAgents: 'मेरे एजेंट',
            marketplace: 'मार्केटप्लेस',
            settings: 'सेटिंग्स',
            adminDashboard: 'एडमिन डैशबोर्ड',
            notifications: 'सूचनाएं',
            personalProfile: 'व्यक्तिगत प्रोफ़ाइल',
            helpFaq: 'सहायता और अक्सर पूछे जाने वाले प्रश्न',
            signOut: 'साइन आउट',
            language: 'भाषा',
            mode: 'मोड',
            light: 'लाइट',
            dark: 'डार्क',
            activeConnection: 'सक्रिय कनेक्शन',
            typeMessage: 'अपना सुरक्षित संदेश टाइप करें...',
            privateSupport: 'निजी सहायता',
            secureProtocol: 'सुरक्षित प्रोटोकॉल सक्रिय',
            history: 'इतिहास',
            newInstance: 'नया इंस्टेंस',
            memoryEmpty: 'मेमोरी खाली है',
            initializeLogic: 'लॉजिक प्रारंभ करें',
            chatGreeting: 'आपका उन्नत एआई एजेंट बातचीत के लिए तैयार है। आज हम आपके वर्कफ़्लो को कैसे अनुकूलित कर सकते हैं?',
            askPlaceholder: 'आइसा से पूछें...',
            my: 'मेरे',
            agentsHeading: 'एजेंट',
            manageAgentsDesc: 'अपने एआई एजेंटों के संग्रह का प्रबंधन करें।',
            docs: 'दस्तावेज़',
            use: 'उपयोग करें',
            info: 'जानकारी',
            marketplaceHeading: 'एआई मॉल मार्केटप्लेस',
            marketplaceSubheading: 'बुद्धिमान एजेंटों की खोज करें',
            aiAgents: 'एआई एजेंट',
            searchPlaceholder: 'एजेंट खोजें...',
            viewInfo: 'जानकारी देखें',
            notificationsHeading: 'सूचनाएं',
            notificationsDesc: 'अपने नवीनतम अलर्ट के साथ अपडेट रहें।',
            markAsRead: 'पढ़ा हुआ मानें',
            delete: 'हटाएं',
            noNotificationsTitle: 'शून्य अनुक्रम',
            noNotificationsDesc: 'कोई सूचना नहीं मिली। आपका सिस्टम वर्तमान में पूर्ण स्थिरता पर है।',
            onlineReady: 'ऑनलाइन और तैयार',
            processingReality: 'प्रक्रिया चल रही है',
            synced: 'सिंक किया गया',
            untitledSession: 'बिना शीर्षक वाला सत्र',
            cancel: 'रद्द करें',
            subscribeNow: 'अभी सब्सक्राइब करें'
        },
        es: {
            title: 'Español (Spanish)',
            chat: 'Chat',
            myAgents: 'Mis Agentes',
            marketplace: 'Mercado',
            settings: 'Ajustes',
            adminDashboard: 'Panel de Admin',
            notifications: 'Notificaciones',
            personalProfile: 'Perfil Personal',
            helpFaq: 'Ayuda y FAQ',
            signOut: 'Cerrar Sesión',
            language: 'Idioma',
            mode: 'Modo',
            light: 'CLARO',
            dark: 'OSCURO',
            activeConnection: 'Conexión Activa',
            typeMessage: 'Escribe tu mensaje seguro...',
            privateSupport: 'Soporte Privado',
            secureProtocol: 'PROTOCOLO SEGURO ACTIVO',
            history: 'Historial',
            newInstance: 'Nueva Instancia',
            memoryEmpty: 'Memoria Vacía',
            initializeLogic: 'INICIALIZAR LÓGICA',
            chatGreeting: 'Tu agente de IA avanzado está calibrado y listo para interactuar. ¿Cómo podemos optimizar tu flujo de trabajo hoy?',
            askPlaceholder: 'Preguntar a Aisa...',
            my: 'Mis',
            agentsHeading: 'Agentes.',
            manageAgentsDesc: 'Administra tu colección de agentes de IA.',
            docs: 'Docs',
            use: 'USAR',
            info: 'Info',
            marketplaceHeading: 'MERCADO AI MALL',
            marketplaceSubheading: 'DESCUBRE AGENTES INTELIGENTES',
            aiAgents: 'AGENTES DE IA',
            searchPlaceholder: 'BUSCAR AGENTES...',
            viewInfo: 'VER INFO',
            notificationsHeading: 'Notificaciones',
            notificationsDesc: 'Mantente al día con tus últimas alertas.',
            markAsRead: 'MARCAR COMO LEÍDO',
            delete: 'ELIMINAR',
            noNotificationsTitle: 'Secuencia de Vacío Nulo',
            noNotificationsDesc: 'No se detectaron transmisiones neuronales. Tu ecosistema está alcanzando su estabilidad máxima.',
            onlineReady: 'En línea y listo',
            processingReality: 'Procesando realidad',
            synced: 'SINCRONIZADO',
            untitledSession: 'Sesión sin título',
            cancel: 'CANCELAR',
            subscribeNow: 'SUSCRIBIRSE AHORA'
        }
    };

    const handleSetLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('preferredLanguage', lang);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ t, language, setLanguage: handleSetLanguage, languages: translations }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
